name: Type check & lint

on: [pull_request] # we want the workflow to trigger on commits to PRs only

jobs: # each workflow consists of 1+ jobs; by default, all jobs run in parallel
  check: # job name
    runs-on: ubuntu-latest # host's operating system

    steps: # each job consists of 1+ steps
      - name: Checkout commit # download the code from triggering commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Enable corepack
        # # Fix for broken corepack - https://github.com/pnpm/pnpm/issues/9029
        run: npm install -g corepack && corepack enable

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: pnpm install

      - name: Run CI
        run: pnpm run-ci

      - name: Run typecheck
        run: pnpm typecheck